%% Angle-only check without impact-time constraint for the current case
clear; clc; close all;
set(groot,'defaultFigureVisible','off');

baseDir=fileparts(mfilename('fullpath'));
resultsDir=fullfile(baseDir,'results');
if ~exist(resultsDir,'dir'), mkdir(resultsDir); end

skipClearOverride=true;
skipControllerComparisonOverride=true;
angleOnlyModeOverride=true;
impactGammaDegOverride=30;
angleOnlyMaxTimeOverride=50;
rdOverride=1.5;
deltaAccelMaxOverride=5;
resultSuffixOverride='angle_no_time_dA_5_main';
run(fullfile(baseDir,'run_stationary_target_demo.m'));

summaryPath=fullfile(resultsDir,'angle_only_no_time_current_summary.csv');
fid=fopen(summaryPath,'w');
fprintf(fid,['case,rd,delta_accel_max,nominal_ok,nominal_time_s,nominal_miss_m,', ...
    'nominal_angle_error_deg,nominal_max_a,stress_ok,stress_time_s,', ...
    'stress_miss_m,stress_angle_error_deg,stress_max_a,', ...
    'nominal_max_delta_a,stress_max_delta_a,nominal_qp_failures,stress_qp_failures\n']);
fprintf(fid,['"angle-only-no-time-30deg",%.8f,%.8f,%d,%.8f,%.8f,%.8f,%.8f,', ...
    '%d,%.8f,%.8f,%.8f,%.8f,%.8f,%.8f,%d,%d\n'], ...
    rdOverride,deltaAccelMaxOverride, ...
    nominal.metrics.impactSatisfied,nominal.metrics.impactTime_s, ...
    nominal.metrics.impactRange_m,nominal.metrics.impactHeadingError_deg, ...
    nominal.metrics.maxAcceleration_mps2, ...
    stress.metrics.impactSatisfied,stress.metrics.impactTime_s, ...
    stress.metrics.impactRange_m,stress.metrics.impactHeadingError_deg, ...
    stress.metrics.maxAcceleration_mps2, ...
    nominal.metrics.maxAccelerationDelta_mps2, ...
    stress.metrics.maxAccelerationDelta_mps2, ...
    nominal.metrics.qpFailures,stress.metrics.qpFailures);
fclose(fid);

fprintf('\nAngle-only no-time summary saved to %s\n',summaryPath);
