%% Time-constraint tuning study for stationary-target Koopman guidance
clear; clc; close all;
set(groot,'defaultFigureVisible','off');

baseDir=fileparts(mfilename('fullpath'));
resultsDir=fullfile(baseDir,'results');
if ~exist(resultsDir,'dir'), mkdir(resultsDir); end

cases=struct( ...
    'name',{'baseline-current','h50-progress','h70-progress','h70-low-smoothing'}, ...
    'suffix',{'tune_baseline_current','tune_h50_progress','tune_h70_progress', ...
        'tune_h70_low_smoothing'}, ...
    'N',{35,50,70,70}, ...
    'nSteps',{90,120,150,150}, ...
    'Qx',{[600,900,35],[3500,900,35],[8000,900,35],[10000,900,35]}, ...
    'Qterminal',{[70000,90000,1200],[250000,90000,1200], ...
        [700000,90000,1200],[900000,90000,1200]}, ...
    'Rbar',{0.06,0.045,0.035,0.025}, ...
    'Rd',{1.5,0.9,0.55,0.25}, ...
    'Slack',{[2e6,2e6,5e5],[8e7,2e6,5e5], ...
        [2e8,2e6,5e5],[5e8,2e6,5e5]}, ...
    'SeqIter',{3,3,4,4});

summary=repmat(struct('name','','suffix','','impactSatisfied',false, ...
    'miss_m',nan,'angle_error_deg',nan,'mean_solve_ms',nan, ...
    'max_solve_ms',nan,'qp_failures',nan,'tau_slack',nan, ...
    'y_slack',nan,'theta_slack',nan),1,numel(cases));

for i=1:numel(cases)
    fprintf('\nRunning tuning case %d/%d: %s\n',i,numel(cases),cases(i).name);
    skipClearOverride=true;
    skipControllerComparisonOverride=true;
    resultSuffixOverride=cases(i).suffix;
    horizonOverride=cases(i).N;
    nStepsOverride=cases(i).nSteps;
    qxOverride=cases(i).Qx;
    qterminalOverride=cases(i).Qterminal;
    rbarScaleOverride=cases(i).Rbar;
    rdOverride=cases(i).Rd;
    slackPenaltyOverride=cases(i).Slack;
    seqIterationsOverride=cases(i).SeqIter;
    run(fullfile(baseDir,'run_stationary_target_demo.m'));

    summary(i).name=cases(i).name;
    summary(i).suffix=cases(i).suffix;
    summary(i).impactSatisfied=nominal.metrics.impactSatisfied;
    summary(i).miss_m=nominal.metrics.impactRange_m;
    summary(i).angle_error_deg=nominal.metrics.impactHeadingError_deg;
    summary(i).mean_solve_ms=nominal.metrics.meanSolveTime_ms;
    summary(i).max_solve_ms=nominal.metrics.maxSolveTime_ms;
    summary(i).qp_failures=nominal.metrics.qpFailures;
    summary(i).tau_slack=nominal.metrics.maxTerminalSlack(1);
    summary(i).y_slack=nominal.metrics.maxTerminalSlack(2);
    summary(i).theta_slack=nominal.metrics.maxTerminalSlack(3);
end

write_tuning_summary(summary,fullfile(resultsDir,'time_constraint_tuning_summary.csv'));
fprintf('\nTuning summary saved to %s\n', ...
    fullfile(resultsDir,'time_constraint_tuning_summary.csv'));

function write_tuning_summary(summary,path)
    fid=fopen(path,'w');
    fprintf(fid,['case,suffix,satisfied,miss_m,angle_error_deg,mean_solve_ms,', ...
        'max_solve_ms,qp_failures,tau_slack,y_slack,theta_slack\n']);
    for i=1:numel(summary)
        fprintf(fid,'"%s","%s",%d,%.8f,%.8f,%.8f,%.8f,%d,%.8e,%.8e,%.8e\n', ...
            summary(i).name,summary(i).suffix,summary(i).impactSatisfied, ...
            summary(i).miss_m,summary(i).angle_error_deg, ...
            summary(i).mean_solve_ms,summary(i).max_solve_ms, ...
            summary(i).qp_failures,summary(i).tau_slack,summary(i).y_slack, ...
            summary(i).theta_slack);
    end
    fclose(fid);
end
